// Package daemon implements the long-running kvnode process: a libp2p host,
// a hashicorp/raft node backed by pkg/kvfsm/pkg/store, and a pkg/ipc server
// that a local mage CLI invocation drives with add/set/get requests.
//
// A daemon always starts "unconfigured": it has an identity and a raft
// instance, but no cluster role until it receives an ipcproto.ActionAdd
// request telling it whether to bootstrap as the cluster's sole leader or
// to join an existing leader. This lets the same binary serve every
// `mage addnode` case (new leader, new follower, or rejoining after a
// restart) with identical startup code.
package daemon

import (
	"bufio"
	"context"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/hashicorp/raft"
	raftboltdb "github.com/hashicorp/raft-boltdb/v2"
	"github.com/libp2p/go-libp2p"
	"github.com/libp2p/go-libp2p/core/crypto"
	lp2phost "github.com/libp2p/go-libp2p/core/host"
	"github.com/libp2p/go-libp2p/core/network"
	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/libp2p/go-libp2p/core/protocol"
	v2relay "github.com/libp2p/go-libp2p/p2p/protocol/circuitv2/relay"
	"github.com/multiformats/go-multiaddr"
	manet "github.com/multiformats/go-multiaddr/net"

	"github.com/gofsd/libp2p-pebble-raft/pkg/ipc"
	"github.com/gofsd/libp2p-pebble-raft/pkg/ipcproto"
	"github.com/gofsd/libp2p-pebble-raft/pkg/kvfsm"
	"github.com/gofsd/libp2p-pebble-raft/pkg/rafttransport"
	"github.com/gofsd/libp2p-pebble-raft/pkg/registry"
	"github.com/gofsd/libp2p-pebble-raft/pkg/store"
)

// JoinProtocolID is the libp2p protocol a joining node uses to ask an
// existing leader to add it as a voter.
const JoinProtocolID = protocol.ID("/libp2p-pebble-raft/join/1.0.0")

// ForwardProtocolID is the libp2p protocol a non-leader node uses to relay
// a Set to the current raft leader on the caller's behalf. Needed because
// pkg/ipc is a same-machine-only protocol -- a node has no other way to
// reach whichever peer is actually the raft leader -- and raft itself
// deliberately has no client-request forwarding built in; that's left to
// the application. In particular, the Android build of this project runs
// as a follower with no separate "find the leader" step available to its
// UI, so every Set it issues needs this to reach the leader at all.
const ForwardProtocolID = protocol.ID("/libp2p-pebble-raft/forward-set/1.0.0")

// ForwardJoinProtocolID is the libp2p protocol a non-leader node uses to
// relay a Join request to the current raft leader on the joining node's
// behalf, mirroring ForwardProtocolID's role for Set and for the same
// reason: raft leadership can move to any voter at any time -- this
// project watched it happen mid-session -- so whichever cluster member a
// new node was told to join through (e.g. a leader address baked into an
// Android build at compile time) may no longer be the leader by the time
// it actually tries.
const ForwardJoinProtocolID = protocol.ID("/libp2p-pebble-raft/forward-join/1.0.0")

// ReadyFileName is written to Config.DataDir once the daemon's host and IPC
// server are up, so the spawning `mage addnode` can learn the node's peer id
// and listen addresses without parsing stdout.
const ReadyFileName = "ready.json"

// Config configures a single node process.
type Config struct {
	DataDir string // root directory for this node's identity, pebble, and raft data
	KeyPath string // libp2p identity key (already generated by the caller)

	// ListenPort is the TCP/QUIC port to listen on. 0 (the default) picks an
	// ephemeral port, fine for same-machine/LAN use. A publicly reachable
	// deployment should pin this to a known port so it can be opened in a
	// firewall/security group.
	ListenPort int

	// RelayService makes this node act as a circuit-relay v2 point for
	// other nodes that can't be dialed directly (the "worst case" NAT
	// fallback) and forces it to advertise itself as publicly reachable.
	// Only enable this on a node known to actually have a public,
	// unfiltered address -- e.g. the leader deployed on a public VPS.
	// Every node, regardless of this flag, can still *use* a relay
	// (EnableRelay/EnableHolePunching are always on); this flag only
	// controls whether it also serves as one for others.
	RelayService bool

	// RelayPeer is a known circuit-relay v2 server's multiaddr (a node
	// running with RelayService=true) this node should proactively reserve
	// a relay slot through, so it ends up with a /p2p-circuit address that
	// someone can dial it on even though it has no directly-dialable
	// address of its own -- e.g. a phone on a cellular connection behind
	// carrier-grade NAT, which blocks *inbound* connections entirely.
	// EnableRelay/EnableHolePunching (always on regardless of this field)
	// only let a node *use* a relay connection someone else already set
	// up; without a static relay target here, a node that nothing can dial
	// directly has no way to make its own reservation, and ends up
	// advertising only addresses that raft's leader can never use to send
	// it AppendEntries -- leaving it permanently stuck as a voter that
	// never learns who the leader is. Leave empty for a node with a real
	// public or otherwise directly-dialable address, where a reservation
	// would just be wasted overhead.
	RelayPeer string

	// Raft timing knobs. Zero means "use hashicorp/raft's own default"
	// (1s heartbeat/election, 50ms commit, 500ms leader lease) -- values
	// the raft project itself considers safe for real networks, not just
	// a fast LAN/loopback. Override with smaller values only where the
	// network genuinely warrants it (e.g. same-machine integration
	// tests): tightening these for a real WAN deployment is what causes
	// spurious "leadership lost" elections when latency/jitter occasionally
	// exceeds an aggressive timeout, especially in a small cluster where
	// every node's vote is required.
	HeartbeatTimeout   time.Duration
	ElectionTimeout    time.Duration
	CommitTimeout      time.Duration
	LeaderLeaseTimeout time.Duration
}

// Node is a running daemon instance. Its raft/transport fields are nil
// until the first ipcproto.ActionAdd request initializes them (see
// initRaft): constructing raft.NewRaft starts its election-timeout loop
// immediately, so doing that unconditionally at process startup -- before
// mage has had a chance to deliver the Add request that decides whether
// this node bootstraps or joins -- creates a race where the node times out
// waiting for a leader, becomes a candidate, and bumps its persisted term.
// That alone makes raft.HasExistingState true and BootstrapCluster then
// fails with "bootstrap only works on new clusters". Deferring
// raft.NewRaft to initRaft, invoked synchronously inside the Add handler,
// closes that window.
type Node struct {
	cfg    Config
	host   lp2phost.Host
	store  *store.Store
	peerID string

	logStore  *raftboltdb.BoltStore
	snapStore raft.SnapshotStore

	mu              sync.RWMutex
	raft            *raft.Raft
	transport       *raft.NetworkTransport
	electionTimeout time.Duration // the effective value raft is actually using, set by initRaft
}

// Run starts a node and blocks, serving IPC requests, until ctx is
// cancelled. It always returns a non-nil error except on clean shutdown via
// ctx cancellation.
func Run(ctx context.Context, cfg Config) error {
	n, err := start(cfg)
	if err != nil {
		return err
	}
	defer n.shutdown()

	// A node that already has persisted raft state -- because it was
	// bootstrapped or joined before, e.g. across a restart -- doesn't need
	// (and, since BootstrapCluster now correctly refuses a non-empty log,
	// can't use) an ActionAdd to become operational again: raft.NewRaft
	// recovers the last known configuration and log from disk on its own.
	// Resume immediately so Set/Get work right away, with no coordination
	// step at all, as long as this node is still reachable at whatever
	// address that recovered configuration expects (true if -listen-port
	// is pinned across restarts). A caller that also needs to re-announce
	// a changed address to the current leader still sends an ActionAdd
	// with a leader address; handleAdd's join path works whether or not
	// this already ran, since initRaft is idempotent.
	hasState, err := raft.HasExistingState(n.logStore, n.logStore, n.snapStore)
	if err != nil {
		return fmt.Errorf("daemon: check existing raft state: %w", err)
	}
	if hasState {
		if _, err := n.initRaft(); err != nil {
			return fmt.Errorf("daemon: resume raft: %w", err)
		}
	}

	if err := n.writeReadyFile(); err != nil {
		return fmt.Errorf("daemon: write ready file: %w", err)
	}

	return ipc.Serve(ctx, n.peerID, n.handle)
}

func start(cfg Config) (*Node, error) {
	if err := os.MkdirAll(cfg.DataDir, 0o755); err != nil {
		return nil, fmt.Errorf("daemon: create data dir: %w", err)
	}

	priv, err := loadKey(cfg.KeyPath)
	if err != nil {
		return nil, fmt.Errorf("daemon: load identity: %w", err)
	}
	peerID, err := peer.IDFromPrivateKey(priv)
	if err != nil {
		return nil, fmt.Errorf("daemon: derive peer id: %w", err)
	}

	h, err := newHost(priv, cfg)
	if err != nil {
		return nil, fmt.Errorf("daemon: create libp2p host: %w", err)
	}

	pebbleDir := filepath.Join(cfg.DataDir, "pebble")
	st, err := store.Open(pebbleDir)
	if err != nil {
		h.Close()
		return nil, fmt.Errorf("daemon: open store: %w", err)
	}

	raftDir := filepath.Join(cfg.DataDir, "raft")
	if err := os.MkdirAll(raftDir, 0o755); err != nil {
		st.Close()
		h.Close()
		return nil, fmt.Errorf("daemon: create raft dir: %w", err)
	}

	logStore, err := raftboltdb.NewBoltStore(filepath.Join(raftDir, "raft.db"))
	if err != nil {
		st.Close()
		h.Close()
		return nil, fmt.Errorf("daemon: open raft log store: %w", err)
	}

	snapDir := filepath.Join(raftDir, "snapshots")
	if err := os.MkdirAll(snapDir, 0o755); err != nil {
		st.Close()
		h.Close()
		return nil, err
	}
	snapStore, err := raft.NewFileSnapshotStore(snapDir, 2, io.Discard)
	if err != nil {
		st.Close()
		h.Close()
		return nil, fmt.Errorf("daemon: open snapshot store: %w", err)
	}

	n := &Node{
		cfg:       cfg,
		host:      h,
		store:     st,
		peerID:    peerID.String(),
		logStore:  logStore,
		snapStore: snapStore,
	}
	h.SetStreamHandler(JoinProtocolID, n.handleJoinStream)
	h.SetStreamHandler(ForwardProtocolID, n.handleForwardSetStream)
	h.SetStreamHandler(ForwardJoinProtocolID, n.handleForwardJoinStream)
	return n, nil
}

// newHost builds this node's libp2p host. Every node gets relay-client and
// hole-punching capability unconditionally, so it can be dialed through
// (or dial through) a circuit relay when a direct connection isn't
// possible -- the "worst case" NAT fallback. A node only advertises itself
// as a relay *for others* (RelayService) and forces public reachability
// when the caller knows it actually has one, e.g. the leader on a public
// VPS; the resource limits mirror the standalone relay in
// pkg/raft/node.go's StartRelayNode.
func newHost(priv crypto.PrivKey, cfg Config) (lp2phost.Host, error) {
	opts := []libp2p.Option{
		libp2p.Identity(priv),
		libp2p.ListenAddrStrings(
			fmt.Sprintf("/ip4/0.0.0.0/tcp/%d", cfg.ListenPort),
			fmt.Sprintf("/ip4/0.0.0.0/udp/%d/quic-v1", cfg.ListenPort),
		),
		libp2p.EnableRelay(),
		libp2p.EnableHolePunching(),
	}

	if cfg.RelayService {
		rc := v2relay.DefaultResources()
		rc.Limit = &v2relay.RelayLimit{
			Duration: time.Hour,
			Data:     1 << 30, // 1 GB
		}
		rc.ReservationTTL = time.Hour
		rc.MaxReservations = 256
		rc.MaxCircuits = 256
		rc.BufferSize = 4096

		opts = append(opts,
			libp2p.EnableRelayService(v2relay.WithResources(rc)),
			libp2p.ForceReachabilityPublic(),
		)
	}

	if cfg.RelayPeer != "" {
		maddr, err := multiaddr.NewMultiaddr(cfg.RelayPeer)
		if err != nil {
			return nil, fmt.Errorf("invalid relay peer address %q: %w", cfg.RelayPeer, err)
		}
		info, err := peer.AddrInfoFromP2pAddr(maddr)
		if err != nil {
			return nil, fmt.Errorf("relay peer address %q missing peer id: %w", cfg.RelayPeer, err)
		}
		opts = append(opts, libp2p.EnableAutoRelayWithStaticRelays([]peer.AddrInfo{*info}))
	}

	return libp2p.New(opts...)
}

// initRaft lazily constructs the raft transport and raft.Raft instance. It
// must be called at most once, synchronously, from the ActionAdd handler.
func (n *Node) initRaft() (*raft.Raft, error) {
	n.mu.Lock()
	defer n.mu.Unlock()
	if n.raft != nil {
		return n.raft, nil
	}

	transport := rafttransport.NewTransport(n.host, 10*time.Second)

	raftConf := raft.DefaultConfig()
	raftConf.LocalID = raft.ServerID(n.peerID)
	if n.cfg.HeartbeatTimeout > 0 {
		raftConf.HeartbeatTimeout = n.cfg.HeartbeatTimeout
	}
	if n.cfg.ElectionTimeout > 0 {
		raftConf.ElectionTimeout = n.cfg.ElectionTimeout
	}
	if n.cfg.CommitTimeout > 0 {
		raftConf.CommitTimeout = n.cfg.CommitTimeout
	}
	if n.cfg.LeaderLeaseTimeout > 0 {
		raftConf.LeaderLeaseTimeout = n.cfg.LeaderLeaseTimeout
	}
	if logFile, err := os.OpenFile(filepath.Join(n.cfg.DataDir, "raft.log"), os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644); err == nil {
		raftConf.LogOutput = logFile
	}

	fsm := kvfsm.New(n.store)
	rf, err := raft.NewRaft(raftConf, fsm, n.logStore, n.logStore, n.snapStore, transport)
	if err != nil {
		transport.Close()
		return nil, fmt.Errorf("daemon: create raft node: %w", err)
	}

	n.raft = rf
	n.transport = transport
	n.electionTimeout = raftConf.ElectionTimeout
	return rf, nil
}

// getRaft returns the raft instance if initRaft has already run.
func (n *Node) getRaft() *raft.Raft {
	n.mu.RLock()
	defer n.mu.RUnlock()
	return n.raft
}

func loadKey(keyPath string) (crypto.PrivKey, error) {
	data, err := os.ReadFile(keyPath)
	if err != nil {
		return nil, fmt.Errorf("read key file %s: %w", keyPath, err)
	}
	raw, err := hex.DecodeString(string(data))
	if err != nil {
		return nil, fmt.Errorf("decode key file %s: %w", keyPath, err)
	}
	return crypto.UnmarshalPrivateKey(raw)
}

func (n *Node) shutdown() {
	n.mu.Lock()
	rf, transport := n.raft, n.transport
	n.mu.Unlock()

	if rf != nil {
		rf.Shutdown()
	}
	if transport != nil {
		transport.Close()
	}
	if n.store != nil {
		n.store.Close()
	}
	if n.host != nil {
		n.host.Close()
	}
}

// advertisedAddrs returns this node's dialable multiaddrs, each including a
// trailing /p2p/<peer-id> component.
// advertisedAddrs returns this node's own dialable addresses, best first:
// this is what gets baked into raft's persisted cluster configuration
// (index [0], for both a bootstrapping leader's own address and a joining
// follower's self-reported address) and what a peer that has never
// connected to this node before -- e.g. after a restart tears down any
// existing connection -- has to work with to dial it fresh.
//
// n.host.Addrs() carries no ordering guarantee that favors reachability, so
// a multi-homed host (a VPS with both a public IP and a private/VPN
// interface, like the one this project targets for a real remote
// deployment) can easily end up with a private address in [0] purely by
// interface enumeration order. That address is often not just suboptimal
// but entirely undialable by anyone outside that private network -- and
// unlike the peerstore, which can accumulate additional observed addresses
// from a successful connection, raft's configuration stores exactly one
// address per voter, so getting it wrong here is not recoverable by any
// other layer once persisted. Sort public addresses first, then
// private/unspecified, then loopback last (only useful for same-machine
// setups, and worse than everything else for a real multi-host one).
func (n *Node) advertisedAddrs() []string {
	hostAddrs := n.host.Addrs()

	const (
		scorePublic = iota
		scoreRelay
		scoreOther
		scoreLoopback
	)
	score := func(a multiaddr.Multiaddr) int {
		switch {
		case manet.IsPublicAddr(a):
			return scorePublic
		// A /p2p-circuit address is a relay reservation (see Config.RelayPeer):
		// unlike a raw private/NAT address, it's actually dialable by
		// whoever needs to reach this node, so it belongs ahead of the
		// "other" tier even though it isn't a direct address either.
		case strings.Contains(a.String(), "/p2p-circuit"):
			return scoreRelay
		case manet.IsIPLoopback(a):
			return scoreLoopback
		default:
			return scoreOther
		}
	}
	sorted := make([]multiaddr.Multiaddr, len(hostAddrs))
	copy(sorted, hostAddrs)
	sort.SliceStable(sorted, func(i, j int) bool { return score(sorted[i]) < score(sorted[j]) })

	addrs := make([]string, 0, len(sorted))
	for _, a := range sorted {
		addrs = append(addrs, fmt.Sprintf("%s/p2p/%s", a, n.peerID))
	}
	return addrs
}

// awaitRelayAddr waits up to timeout for a /p2p-circuit address -- proof
// the Config.RelayPeer reservation configured in newHost has completed --
// to appear in n.host.Addrs(). A no-op that returns immediately when
// RelayPeer isn't set, since there's then nothing to wait for.
func (n *Node) awaitRelayAddr(timeout time.Duration) {
	if n.cfg.RelayPeer == "" {
		return
	}
	deadline := time.After(timeout)
	ticker := time.NewTicker(200 * time.Millisecond)
	defer ticker.Stop()
	for {
		for _, a := range n.host.Addrs() {
			if strings.Contains(a.String(), "/p2p-circuit") {
				return
			}
		}
		select {
		case <-deadline:
			return
		case <-ticker.C:
		}
	}
}

// ReadyInfo is the content of ReadyFileName: what the spawning `mage
// addnode` needs to learn about a freshly started node before it can
// register it and trigger its ActionAdd bootstrap.
type ReadyInfo struct {
	PeerID      string   `json:"peer_id"`
	ListenAddrs []string `json:"listen_addrs"`
}

// ReadReadyFile reads and parses the ReadyFileName written by a node in
// dataDir. It returns an error (wrapping fs.ErrNotExist) if the node hasn't
// written it yet.
func ReadReadyFile(dataDir string) (ReadyInfo, error) {
	var info ReadyInfo
	data, err := os.ReadFile(filepath.Join(dataDir, ReadyFileName))
	if err != nil {
		return info, err
	}
	if err := json.Unmarshal(data, &info); err != nil {
		return info, fmt.Errorf("daemon: parse ready file: %w", err)
	}
	return info, nil
}

func (n *Node) writeReadyFile() error {
	info := ReadyInfo{PeerID: n.peerID, ListenAddrs: n.advertisedAddrs()}
	data, err := json.Marshal(info)
	if err != nil {
		return err
	}
	path := filepath.Join(n.cfg.DataDir, ReadyFileName)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// handle dispatches one decoded ipcproto.Request to the appropriate raft/
// store operation and returns the Response to send back.
func (n *Node) handle(ctx context.Context, req ipcproto.Request) ipcproto.Response {
	switch req.Action {
	case ipcproto.ActionAdd:
		return n.handleAdd(ctx, req)
	case ipcproto.ActionSet:
		return n.handleSet(ctx, req)
	case ipcproto.ActionGet:
		return n.handleGet(ctx, req)
	default:
		return ipcproto.NewResponse(ipcproto.StatusError, fmt.Sprintf("unknown action %d", req.Action))
	}
}

func (n *Node) handleAdd(ctx context.Context, req ipcproto.Request) ipcproto.Response {
	leaderPeerID := req.KeyString()

	rf, err := n.initRaft()
	if err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, "init raft: "+err.Error())
	}

	if leaderPeerID == "" {
		cfg := raft.Configuration{
			Servers: []raft.Server{{
				Suffrage: raft.Voter,
				ID:       raft.ServerID(n.peerID),
				Address:  raft.ServerAddress(n.advertisedAddrs()[0]),
			}},
		}
		if err := rf.BootstrapCluster(cfg).Error(); err != nil {
			return ipcproto.NewResponse(ipcproto.StatusError, "bootstrap: "+err.Error())
		}
		// BootstrapCluster only guarantees the configuration was persisted,
		// not that self-election has completed yet. A follower's join
		// request (handleJoinStream) requires State() == Leader, so make
		// the Add response wait for that instead of racing a subsequent
		// `mage addnode <leaderPeerID>` against this node's own election.
		// Scale the wait off the actual configured election timeout rather
		// than a fixed constant, so a longer WAN-tuned timeout still gets a
		// comfortable margin instead of being raced against a hardcoded window.
		if _, err := n.awaitLeader(10 * n.electionTimeout); err != nil {
			return ipcproto.NewResponse(ipcproto.StatusError, "await self-election: "+err.Error())
		}
		return ipcproto.NewResponse(ipcproto.StatusOK, n.peerID)
	}

	// leaderPeerID is either a full multiaddr (a leader on another machine,
	// e.g. a remote deployment -- there's no shared registry to resolve it
	// from) or a bare peer id created on this same machine, resolved
	// through the local registry.
	leaderAddr := leaderPeerID
	if !registry.IsMultiaddr(leaderPeerID) {
		reg, err := registry.Open()
		if err != nil {
			return ipcproto.NewResponse(ipcproto.StatusError, err.Error())
		}
		leaderAddr, err = reg.ResolveAddress(leaderPeerID)
		if err != nil {
			return ipcproto.NewResponse(ipcproto.StatusError, err.Error())
		}
	}

	if err := n.join(ctx, leaderAddr); err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, "join: "+err.Error())
	}
	return ipcproto.NewResponse(ipcproto.StatusOK, n.peerID)
}

// join asks the leader reachable at leaderAddr to add this node as a voter.
func (n *Node) join(ctx context.Context, leaderAddr string) error {
	maddr, err := multiaddr.NewMultiaddr(leaderAddr)
	if err != nil {
		return fmt.Errorf("invalid leader address %q: %w", leaderAddr, err)
	}
	info, err := peer.AddrInfoFromP2pAddr(maddr)
	if err != nil {
		return fmt.Errorf("leader address %q missing peer id: %w", leaderAddr, err)
	}
	if err := n.host.Connect(ctx, *info); err != nil {
		return fmt.Errorf("connect to leader %s: %w", info.ID, err)
	}

	s, err := n.host.NewStream(ctx, info.ID, JoinProtocolID)
	if err != nil {
		return fmt.Errorf("open join stream to leader %s: %w", info.ID, err)
	}
	defer s.Close()

	// If this node needs a relay reservation to be reachable at all (see
	// Config.RelayPeer), give it a moment to complete before announcing an
	// address: AutoRelay's reservation happens asynchronously in the
	// background from newHost, and raft's configuration stores whatever
	// address we send here permanently -- getting it before the /p2p-circuit
	// address exists means the leader can never actually reach this node.
	n.awaitRelayAddr(15 * time.Second)

	selfAddr := n.advertisedAddrs()[0]
	if _, err := fmt.Fprintf(s, "%s %s\n", n.peerID, selfAddr); err != nil {
		return fmt.Errorf("send join request: %w", err)
	}
	if err := s.CloseWrite(); err != nil {
		return fmt.Errorf("close join request: %w", err)
	}

	scanner := bufio.NewScanner(s)
	if !scanner.Scan() {
		if err := scanner.Err(); err != nil {
			return fmt.Errorf("read join response: %w", err)
		}
		return fmt.Errorf("no response from leader %s", info.ID)
	}
	line := scanner.Text()
	if line == "OK" {
		return nil
	}
	return fmt.Errorf("leader rejected join: %s", line)
}

// handleJoinStream is the leader-side handler for JoinProtocolID: it parses
// "<peer-id> <multiaddr>" from the requester and adds it as a raft voter if
// this node is the leader, or forwards the request to whoever currently is
// (one hop only, over ForwardJoinProtocolID -- see handleForwardJoinStream)
// since the joining node has no other way to learn the real leader.
func (n *Node) handleJoinStream(s network.Stream) {
	defer s.Close()

	joinPeerID, joinAddr, err := parseJoinRequest(s)
	if err != nil {
		fmt.Fprintf(s, "ERR: malformed join request: %v\n", err)
		return
	}

	rf := n.getRaft()
	if rf != nil && rf.State() == raft.Leader {
		fmt.Fprintf(s, "%s\n", addVoterLine(rf, joinPeerID, joinAddr))
		return
	}

	var leaderID raft.ServerID
	if rf != nil {
		_, leaderID = rf.LeaderWithID()
	}
	if leaderID == "" {
		fmt.Fprintf(s, "ERR: not leader\n")
		return
	}

	line, err := n.forwardJoin(context.Background(), leaderID, joinPeerID, joinAddr)
	if err != nil {
		fmt.Fprintf(s, "ERR: forward join: %v\n", err)
		return
	}
	fmt.Fprintf(s, "%s\n", line)
}

// handleForwardJoinStream is the leader-side handler for
// ForwardJoinProtocolID: it adds the requester as a raft voter if this node
// is actually the leader, or reports the current leader without forwarding
// again -- mirroring handleForwardSetStream's single-hop guarantee, which
// rules out a forwarding cycle regardless of how leadership bounces around.
func (n *Node) handleForwardJoinStream(s network.Stream) {
	defer s.Close()

	joinPeerID, joinAddr, err := parseJoinRequest(s)
	if err != nil {
		fmt.Fprintf(s, "ERR: malformed join request: %v\n", err)
		return
	}

	rf := n.getRaft()
	if rf == nil || rf.State() != raft.Leader {
		var leaderID raft.ServerID
		if rf != nil {
			_, leaderID = rf.LeaderWithID()
		}
		fmt.Fprintf(s, "ERR: not leader; current leader is %s (already forwarded once)\n", leaderID)
		return
	}

	fmt.Fprintf(s, "%s\n", addVoterLine(rf, joinPeerID, joinAddr))
}

// parseJoinRequest reads and parses the single "<peer-id> <multiaddr>" line
// that is the wire format shared by JoinProtocolID and ForwardJoinProtocolID.
func parseJoinRequest(s network.Stream) (peerID, addr string, err error) {
	scanner := bufio.NewScanner(s)
	if !scanner.Scan() {
		if err := scanner.Err(); err != nil {
			return "", "", err
		}
		return "", "", fmt.Errorf("empty join request")
	}
	if _, err := fmt.Sscanf(scanner.Text(), "%s %s", &peerID, &addr); err != nil {
		return "", "", err
	}
	return peerID, addr, nil
}

// addVoterLine runs raft.AddVoter for joinPeerID/joinAddr and returns the
// response line to send back over the wire: "OK" or "ERR: <reason>".
func addVoterLine(rf *raft.Raft, joinPeerID, joinAddr string) string {
	if err := rf.AddVoter(raft.ServerID(joinPeerID), raft.ServerAddress(joinAddr), 0, 10*time.Second).Error(); err != nil {
		return fmt.Sprintf("ERR: %v", err)
	}
	return "OK"
}

// forwardJoin relays a join request (joinPeerID, joinAddr) to leaderID over
// ForwardJoinProtocolID and returns its response line verbatim (without the
// trailing newline). Mirrors forwardSet's reasoning: the libp2p host
// already knows how to reach leaderID via this node's own raft transport,
// so no address resolution beyond the peer id is needed.
func (n *Node) forwardJoin(ctx context.Context, leaderID raft.ServerID, joinPeerID, joinAddr string) (string, error) {
	pid, err := peer.Decode(string(leaderID))
	if err != nil {
		return "", fmt.Errorf("invalid leader id %s: %w", leaderID, err)
	}
	s, err := n.host.NewStream(ctx, pid, ForwardJoinProtocolID)
	if err != nil {
		return "", fmt.Errorf("open forward-join stream to leader %s: %w", leaderID, err)
	}
	defer s.Close()

	if _, err := fmt.Fprintf(s, "%s %s\n", joinPeerID, joinAddr); err != nil {
		return "", fmt.Errorf("write to leader %s: %w", leaderID, err)
	}
	if err := s.CloseWrite(); err != nil {
		return "", fmt.Errorf("close write to leader %s: %w", leaderID, err)
	}

	scanner := bufio.NewScanner(s)
	if !scanner.Scan() {
		if err := scanner.Err(); err != nil {
			return "", fmt.Errorf("read response from leader %s: %w", leaderID, err)
		}
		return "", fmt.Errorf("no response from leader %s", leaderID)
	}
	return scanner.Text(), nil
}

// handleSet is the IPC entry point for ActionSet: it applies directly if
// this node is the leader, or forwards to the leader (one hop only) if
// not. Handler is not exported to pkg/ipc directly; see handle's switch.
func (n *Node) handleSet(ctx context.Context, req ipcproto.Request) ipcproto.Response {
	return n.handleSetForward(ctx, req, true)
}

// handleSetForward implements handleSet, plus handleForwardSetStream's
// leader-side answer to an already-forwarded request. allowForward is
// false on that second path so a request can be forwarded at most once:
// if the node it lands on then *also* turns out not to be leader (a
// leadership change mid-flight), it fails outward with a clear error
// instead of forwarding again, which rules out any forwarding cycle
// regardless of how leadership bounces around.
func (n *Node) handleSetForward(ctx context.Context, req ipcproto.Request, allowForward bool) ipcproto.Response {
	// Both wait windows below scale off the actual configured election
	// timeout (not a fixed constant) so a WAN-tuned longer timeout still
	// gets a comfortable margin: Apply itself can legitimately take a full
	// election cycle if the leader steps down and a new one is elected
	// mid-call.
	rf, isLeader, leaderID, err := n.resolveWriteTarget(5 * n.electionTimeout)
	if err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, err.Error())
	}
	if isLeader {
		return n.applySet(rf, req)
	}
	if !allowForward {
		return ipcproto.NewResponse(ipcproto.StatusError, fmt.Sprintf("not leader; current leader is %s (already forwarded once)", leaderID))
	}
	return n.forwardSet(ctx, leaderID, req)
}

func (n *Node) applySet(rf *raft.Raft, req ipcproto.Request) ipcproto.Response {
	cmd := kvfsm.EncodeCommand(kvfsm.OpSet, []byte(req.KeyString()), []byte(req.ValueString()))
	future := rf.Apply(cmd, 10*n.electionTimeout)
	if err := future.Error(); err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, err.Error())
	}
	if res, ok := future.Response().(kvfsm.ApplyResult); ok && res.Err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, res.Err.Error())
	}
	return ipcproto.NewResponse(ipcproto.StatusOK, "")
}

// forwardSet relays req (an ActionSet) to leaderID over ForwardProtocolID
// and returns its response verbatim. The libp2p host already has an open
// connection/known address for leaderID -- it's the peer this node's own
// raft transport talks to for AppendEntries -- so no address resolution
// is needed beyond the peer id itself.
func (n *Node) forwardSet(ctx context.Context, leaderID raft.ServerID, req ipcproto.Request) ipcproto.Response {
	pid, err := peer.Decode(string(leaderID))
	if err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, fmt.Sprintf("forward set: invalid leader id %s: %v", leaderID, err))
	}
	s, err := n.host.NewStream(ctx, pid, ForwardProtocolID)
	if err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, fmt.Sprintf("forward set to leader %s: %v", leaderID, err))
	}
	defer s.Close()

	buf := req.Encode()
	if _, err := s.Write(buf[:]); err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, fmt.Sprintf("forward set: write to leader %s: %v", leaderID, err))
	}
	if err := s.CloseWrite(); err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, fmt.Sprintf("forward set: close write to leader %s: %v", leaderID, err))
	}

	respBuf := make([]byte, ipcproto.ResponseSize)
	if _, err := io.ReadFull(s, respBuf); err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, fmt.Sprintf("forward set: read response from leader %s: %v", leaderID, err))
	}
	resp, err := ipcproto.DecodeResponse(respBuf)
	if err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, fmt.Sprintf("forward set: decode response: %v", err))
	}
	return resp
}

// handleForwardSetStream is the leader-side handler for ForwardProtocolID:
// it decodes a full ipcproto.Request (always an ActionSet) and answers it
// exactly like a local Set would, with forwarding disabled (see
// handleSetForward's allowForward doc).
func (n *Node) handleForwardSetStream(s network.Stream) {
	defer s.Close()

	buf := make([]byte, ipcproto.RequestSize)
	if _, err := io.ReadFull(s, buf); err != nil {
		return
	}
	req, err := ipcproto.DecodeRequest(buf)
	if err != nil {
		return
	}

	resp := n.handleSetForward(context.Background(), req, false)
	respBuf := resp.Encode()
	s.Write(respBuf[:])
}

func (n *Node) handleGet(_ context.Context, req ipcproto.Request) ipcproto.Response {
	value, err := n.store.Get([]byte(req.KeyString()))
	if err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, err.Error())
	}
	return ipcproto.NewResponse(ipcproto.StatusOK, string(value))
}

// awaitLeader waits up to timeout for this node to become raft leader and
// returns the raft instance once it has. A freshly bootstrapped
// single-voter cluster elects itself almost immediately; this absorbs that
// startup race instead of failing the first Set issued right after
// `mage addnode`.
func (n *Node) awaitLeader(timeout time.Duration) (*raft.Raft, error) {
	deadline := time.After(timeout)
	ticker := time.NewTicker(10 * time.Millisecond)
	defer ticker.Stop()
	for {
		if rf := n.getRaft(); rf != nil && rf.State() == raft.Leader {
			return rf, nil
		}
		select {
		case <-deadline:
			rf := n.getRaft()
			if rf == nil {
				return nil, fmt.Errorf("node has not been added to a cluster yet")
			}
			if _, leaderID := rf.LeaderWithID(); leaderID != "" {
				return nil, fmt.Errorf("not leader; current leader is %s", leaderID)
			}
			return nil, fmt.Errorf("not leader and no leader known")
		case <-ticker.C:
		}
	}
}

// resolveWriteTarget waits (up to timeout) for this node to either become
// raft leader itself or learn who currently is, and reports which. In
// steady state this returns on its very first check, with no waiting at
// all -- the timeout only matters right after bootstrap/join, before
// raft's first election has completed and LeaderWithID is still empty.
func (n *Node) resolveWriteTarget(timeout time.Duration) (rf *raft.Raft, isLeader bool, leaderID raft.ServerID, err error) {
	deadline := time.After(timeout)
	ticker := time.NewTicker(10 * time.Millisecond)
	defer ticker.Stop()
	for {
		if rf := n.getRaft(); rf != nil {
			if rf.State() == raft.Leader {
				return rf, true, "", nil
			}
			if _, id := rf.LeaderWithID(); id != "" {
				return rf, false, id, nil
			}
		}
		select {
		case <-deadline:
			if n.getRaft() == nil {
				return nil, false, "", fmt.Errorf("node has not been added to a cluster yet")
			}
			return nil, false, "", fmt.Errorf("not leader and no leader known")
		case <-ticker.C:
		}
	}
}
