// Package daemon implements the long-running kvnode process: a libp2p host,
// a hashicorp/raft node backed by pkg/kvfsm/pkg/store, and a pkg/ipc server
// that a local mage CLI invocation drives with add/set/get requests.
//
// A daemon always starts "unconfigured": it has an identity and a raft
// instance, but no cluster role until it receives an ipcproto.ActionAdd
// request telling it whether to bootstrap as the cluster's sole leader or
// to join an existing leader. This lets the same binary serve every
// `mage addnode` case (new leader, new follower, or rejoining after a
// restart) with identical startup code.
package daemon

import (
	"bufio"
	"context"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sync"
	"time"

	"github.com/hashicorp/raft"
	raftboltdb "github.com/hashicorp/raft-boltdb/v2"
	"github.com/libp2p/go-libp2p"
	"github.com/libp2p/go-libp2p/core/crypto"
	lp2phost "github.com/libp2p/go-libp2p/core/host"
	"github.com/libp2p/go-libp2p/core/network"
	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/libp2p/go-libp2p/core/protocol"
	"github.com/multiformats/go-multiaddr"

	"github.com/gofsd/libp2p-pebble-raft/pkg/ipc"
	"github.com/gofsd/libp2p-pebble-raft/pkg/ipcproto"
	"github.com/gofsd/libp2p-pebble-raft/pkg/kvfsm"
	"github.com/gofsd/libp2p-pebble-raft/pkg/rafttransport"
	"github.com/gofsd/libp2p-pebble-raft/pkg/registry"
	"github.com/gofsd/libp2p-pebble-raft/pkg/store"
)

// JoinProtocolID is the libp2p protocol a joining node uses to ask an
// existing leader to add it as a voter.
const JoinProtocolID = protocol.ID("/libp2p-pebble-raft/join/1.0.0")

// ReadyFileName is written to Config.DataDir once the daemon's host and IPC
// server are up, so the spawning `mage addnode` can learn the node's peer id
// and listen addresses without parsing stdout.
const ReadyFileName = "ready.json"

// Config configures a single node process.
type Config struct {
	DataDir string // root directory for this node's identity, pebble, and raft data
	KeyPath string // libp2p identity key (already generated by the caller)
}

// Node is a running daemon instance. Its raft/transport fields are nil
// until the first ipcproto.ActionAdd request initializes them (see
// initRaft): constructing raft.NewRaft starts its election-timeout loop
// immediately, so doing that unconditionally at process startup -- before
// mage has had a chance to deliver the Add request that decides whether
// this node bootstraps or joins -- creates a race where the node times out
// waiting for a leader, becomes a candidate, and bumps its persisted term.
// That alone makes raft.HasExistingState true and BootstrapCluster then
// fails with "bootstrap only works on new clusters". Deferring
// raft.NewRaft to initRaft, invoked synchronously inside the Add handler,
// closes that window.
type Node struct {
	cfg    Config
	host   lp2phost.Host
	store  *store.Store
	peerID string

	logStore  *raftboltdb.BoltStore
	snapStore raft.SnapshotStore

	mu        sync.RWMutex
	raft      *raft.Raft
	transport *raft.NetworkTransport
}

// Run starts a node and blocks, serving IPC requests, until ctx is
// cancelled. It always returns a non-nil error except on clean shutdown via
// ctx cancellation.
func Run(ctx context.Context, cfg Config) error {
	n, err := start(cfg)
	if err != nil {
		return err
	}
	defer n.shutdown()

	if err := n.writeReadyFile(); err != nil {
		return fmt.Errorf("daemon: write ready file: %w", err)
	}

	return ipc.Serve(ctx, n.peerID, n.handle)
}

func start(cfg Config) (*Node, error) {
	if err := os.MkdirAll(cfg.DataDir, 0o755); err != nil {
		return nil, fmt.Errorf("daemon: create data dir: %w", err)
	}

	priv, err := loadKey(cfg.KeyPath)
	if err != nil {
		return nil, fmt.Errorf("daemon: load identity: %w", err)
	}
	peerID, err := peer.IDFromPrivateKey(priv)
	if err != nil {
		return nil, fmt.Errorf("daemon: derive peer id: %w", err)
	}

	h, err := libp2p.New(
		libp2p.Identity(priv),
		libp2p.ListenAddrStrings(
			"/ip4/0.0.0.0/tcp/0",
			"/ip4/0.0.0.0/udp/0/quic-v1",
		),
	)
	if err != nil {
		return nil, fmt.Errorf("daemon: create libp2p host: %w", err)
	}

	pebbleDir := filepath.Join(cfg.DataDir, "pebble")
	st, err := store.Open(pebbleDir)
	if err != nil {
		h.Close()
		return nil, fmt.Errorf("daemon: open store: %w", err)
	}

	raftDir := filepath.Join(cfg.DataDir, "raft")
	if err := os.MkdirAll(raftDir, 0o755); err != nil {
		st.Close()
		h.Close()
		return nil, fmt.Errorf("daemon: create raft dir: %w", err)
	}

	logStore, err := raftboltdb.NewBoltStore(filepath.Join(raftDir, "raft.db"))
	if err != nil {
		st.Close()
		h.Close()
		return nil, fmt.Errorf("daemon: open raft log store: %w", err)
	}

	snapDir := filepath.Join(raftDir, "snapshots")
	if err := os.MkdirAll(snapDir, 0o755); err != nil {
		st.Close()
		h.Close()
		return nil, err
	}
	snapStore, err := raft.NewFileSnapshotStore(snapDir, 2, io.Discard)
	if err != nil {
		st.Close()
		h.Close()
		return nil, fmt.Errorf("daemon: open snapshot store: %w", err)
	}

	n := &Node{
		cfg:       cfg,
		host:      h,
		store:     st,
		peerID:    peerID.String(),
		logStore:  logStore,
		snapStore: snapStore,
	}
	h.SetStreamHandler(JoinProtocolID, n.handleJoinStream)
	return n, nil
}

// initRaft lazily constructs the raft transport and raft.Raft instance. It
// must be called at most once, synchronously, from the ActionAdd handler.
func (n *Node) initRaft() (*raft.Raft, error) {
	n.mu.Lock()
	defer n.mu.Unlock()
	if n.raft != nil {
		return n.raft, nil
	}

	transport := rafttransport.NewTransport(n.host, 10*time.Second)

	raftConf := raft.DefaultConfig()
	raftConf.LocalID = raft.ServerID(n.peerID)
	raftConf.HeartbeatTimeout = 300 * time.Millisecond
	raftConf.ElectionTimeout = 300 * time.Millisecond
	raftConf.CommitTimeout = 50 * time.Millisecond
	raftConf.LeaderLeaseTimeout = 250 * time.Millisecond
	if logFile, err := os.OpenFile(filepath.Join(n.cfg.DataDir, "raft.log"), os.O_CREATE|os.O_WRONLY|os.O_APPEND, 0o644); err == nil {
		raftConf.LogOutput = logFile
	}

	fsm := kvfsm.New(n.store)
	rf, err := raft.NewRaft(raftConf, fsm, n.logStore, n.logStore, n.snapStore, transport)
	if err != nil {
		transport.Close()
		return nil, fmt.Errorf("daemon: create raft node: %w", err)
	}

	n.raft = rf
	n.transport = transport
	return rf, nil
}

// getRaft returns the raft instance if initRaft has already run.
func (n *Node) getRaft() *raft.Raft {
	n.mu.RLock()
	defer n.mu.RUnlock()
	return n.raft
}

func loadKey(keyPath string) (crypto.PrivKey, error) {
	data, err := os.ReadFile(keyPath)
	if err != nil {
		return nil, fmt.Errorf("read key file %s: %w", keyPath, err)
	}
	raw, err := hex.DecodeString(string(data))
	if err != nil {
		return nil, fmt.Errorf("decode key file %s: %w", keyPath, err)
	}
	return crypto.UnmarshalPrivateKey(raw)
}

func (n *Node) shutdown() {
	n.mu.Lock()
	rf, transport := n.raft, n.transport
	n.mu.Unlock()

	if rf != nil {
		rf.Shutdown()
	}
	if transport != nil {
		transport.Close()
	}
	if n.store != nil {
		n.store.Close()
	}
	if n.host != nil {
		n.host.Close()
	}
}

// advertisedAddrs returns this node's dialable multiaddrs, each including a
// trailing /p2p/<peer-id> component.
func (n *Node) advertisedAddrs() []string {
	addrs := make([]string, 0, len(n.host.Addrs()))
	for _, a := range n.host.Addrs() {
		addrs = append(addrs, fmt.Sprintf("%s/p2p/%s", a, n.peerID))
	}
	return addrs
}

// ReadyInfo is the content of ReadyFileName: what the spawning `mage
// addnode` needs to learn about a freshly started node before it can
// register it and trigger its ActionAdd bootstrap.
type ReadyInfo struct {
	PeerID      string   `json:"peer_id"`
	ListenAddrs []string `json:"listen_addrs"`
}

// ReadReadyFile reads and parses the ReadyFileName written by a node in
// dataDir. It returns an error (wrapping fs.ErrNotExist) if the node hasn't
// written it yet.
func ReadReadyFile(dataDir string) (ReadyInfo, error) {
	var info ReadyInfo
	data, err := os.ReadFile(filepath.Join(dataDir, ReadyFileName))
	if err != nil {
		return info, err
	}
	if err := json.Unmarshal(data, &info); err != nil {
		return info, fmt.Errorf("daemon: parse ready file: %w", err)
	}
	return info, nil
}

func (n *Node) writeReadyFile() error {
	info := ReadyInfo{PeerID: n.peerID, ListenAddrs: n.advertisedAddrs()}
	data, err := json.Marshal(info)
	if err != nil {
		return err
	}
	path := filepath.Join(n.cfg.DataDir, ReadyFileName)
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o644); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

// handle dispatches one decoded ipcproto.Request to the appropriate raft/
// store operation and returns the Response to send back.
func (n *Node) handle(ctx context.Context, req ipcproto.Request) ipcproto.Response {
	switch req.Action {
	case ipcproto.ActionAdd:
		return n.handleAdd(ctx, req)
	case ipcproto.ActionSet:
		return n.handleSet(ctx, req)
	case ipcproto.ActionGet:
		return n.handleGet(ctx, req)
	default:
		return ipcproto.NewResponse(ipcproto.StatusError, fmt.Sprintf("unknown action %d", req.Action))
	}
}

func (n *Node) handleAdd(ctx context.Context, req ipcproto.Request) ipcproto.Response {
	leaderPeerID := req.KeyString()

	rf, err := n.initRaft()
	if err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, "init raft: "+err.Error())
	}

	if leaderPeerID == "" {
		cfg := raft.Configuration{
			Servers: []raft.Server{{
				Suffrage: raft.Voter,
				ID:       raft.ServerID(n.peerID),
				Address:  raft.ServerAddress(n.advertisedAddrs()[0]),
			}},
		}
		if err := rf.BootstrapCluster(cfg).Error(); err != nil {
			return ipcproto.NewResponse(ipcproto.StatusError, "bootstrap: "+err.Error())
		}
		// BootstrapCluster only guarantees the configuration was persisted,
		// not that self-election has completed yet. A follower's join
		// request (handleJoinStream) requires State() == Leader, so make
		// the Add response wait for that instead of racing a subsequent
		// `mage addnode <leaderPeerID>` against this node's own election.
		if _, err := n.awaitLeader(5 * time.Second); err != nil {
			return ipcproto.NewResponse(ipcproto.StatusError, "await self-election: "+err.Error())
		}
		return ipcproto.NewResponse(ipcproto.StatusOK, n.peerID)
	}

	reg, err := registry.Open()
	if err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, err.Error())
	}
	leaderAddr, err := reg.ResolveAddress(leaderPeerID)
	if err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, err.Error())
	}

	if err := n.join(ctx, leaderAddr); err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, "join: "+err.Error())
	}
	return ipcproto.NewResponse(ipcproto.StatusOK, n.peerID)
}

// join asks the leader reachable at leaderAddr to add this node as a voter.
func (n *Node) join(ctx context.Context, leaderAddr string) error {
	maddr, err := multiaddr.NewMultiaddr(leaderAddr)
	if err != nil {
		return fmt.Errorf("invalid leader address %q: %w", leaderAddr, err)
	}
	info, err := peer.AddrInfoFromP2pAddr(maddr)
	if err != nil {
		return fmt.Errorf("leader address %q missing peer id: %w", leaderAddr, err)
	}
	if err := n.host.Connect(ctx, *info); err != nil {
		return fmt.Errorf("connect to leader %s: %w", info.ID, err)
	}

	s, err := n.host.NewStream(ctx, info.ID, JoinProtocolID)
	if err != nil {
		return fmt.Errorf("open join stream to leader %s: %w", info.ID, err)
	}
	defer s.Close()

	selfAddr := n.advertisedAddrs()[0]
	if _, err := fmt.Fprintf(s, "%s %s\n", n.peerID, selfAddr); err != nil {
		return fmt.Errorf("send join request: %w", err)
	}
	if err := s.CloseWrite(); err != nil {
		return fmt.Errorf("close join request: %w", err)
	}

	scanner := bufio.NewScanner(s)
	if !scanner.Scan() {
		if err := scanner.Err(); err != nil {
			return fmt.Errorf("read join response: %w", err)
		}
		return fmt.Errorf("no response from leader %s", info.ID)
	}
	line := scanner.Text()
	if line == "OK" {
		return nil
	}
	return fmt.Errorf("leader rejected join: %s", line)
}

// handleJoinStream is the leader-side handler for JoinProtocolID: it parses
// "<peer-id> <multiaddr>" from the requester and adds it as a raft voter.
func (n *Node) handleJoinStream(s network.Stream) {
	defer s.Close()

	scanner := bufio.NewScanner(s)
	if !scanner.Scan() {
		fmt.Fprintf(s, "ERR: empty join request\n")
		return
	}
	line := scanner.Text()

	var joinPeerID, joinAddr string
	if _, err := fmt.Sscanf(line, "%s %s", &joinPeerID, &joinAddr); err != nil {
		fmt.Fprintf(s, "ERR: malformed join request: %v\n", err)
		return
	}

	rf := n.getRaft()
	if rf == nil || rf.State() != raft.Leader {
		fmt.Fprintf(s, "ERR: not leader\n")
		return
	}

	if err := rf.AddVoter(raft.ServerID(joinPeerID), raft.ServerAddress(joinAddr), 0, 10*time.Second).Error(); err != nil {
		fmt.Fprintf(s, "ERR: %v\n", err)
		return
	}
	fmt.Fprintf(s, "OK\n")
}

func (n *Node) handleSet(_ context.Context, req ipcproto.Request) ipcproto.Response {
	rf, err := n.awaitLeader(2 * time.Second)
	if err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, err.Error())
	}
	cmd := kvfsm.EncodeCommand(kvfsm.OpSet, []byte(req.KeyString()), []byte(req.ValueString()))
	future := rf.Apply(cmd, 5*time.Second)
	if err := future.Error(); err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, err.Error())
	}
	if res, ok := future.Response().(kvfsm.ApplyResult); ok && res.Err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, res.Err.Error())
	}
	return ipcproto.NewResponse(ipcproto.StatusOK, "")
}

func (n *Node) handleGet(_ context.Context, req ipcproto.Request) ipcproto.Response {
	value, err := n.store.Get([]byte(req.KeyString()))
	if err != nil {
		return ipcproto.NewResponse(ipcproto.StatusError, err.Error())
	}
	return ipcproto.NewResponse(ipcproto.StatusOK, string(value))
}

// awaitLeader waits up to timeout for this node to become raft leader and
// returns the raft instance once it has. A freshly bootstrapped
// single-voter cluster elects itself almost immediately; this absorbs that
// startup race instead of failing the first Set issued right after
// `mage addnode`.
func (n *Node) awaitLeader(timeout time.Duration) (*raft.Raft, error) {
	deadline := time.After(timeout)
	ticker := time.NewTicker(10 * time.Millisecond)
	defer ticker.Stop()
	for {
		if rf := n.getRaft(); rf != nil && rf.State() == raft.Leader {
			return rf, nil
		}
		select {
		case <-deadline:
			rf := n.getRaft()
			if rf == nil {
				return nil, fmt.Errorf("node has not been added to a cluster yet")
			}
			if _, leaderID := rf.LeaderWithID(); leaderID != "" {
				return nil, fmt.Errorf("not leader; current leader is %s", leaderID)
			}
			return nil, fmt.Errorf("not leader and no leader known")
		case <-ticker.C:
		}
	}
}
